# Generated by Django 6.0.7 on 2026-08-07 10:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('birthday', '0002_birthday_author'),
        ('birthday', '0002_birthday_image_alter_birthday_birthday_and_more'),
    ]

    operations = [
    ]
